# Generated by Django 6.0.3 on 2026-06-28 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(choices=[('Araria', 'Araria'), ('Arwal', 'Arwal'), ('Aurangabad', 'Aurangabad'), ('Banka', 'Banka'), ('Begusarai', 'Begusarai'), ('Bhagalpur', 'Bhagalpur'), ('Bhojpur', 'Bhojpur'), ('Buxar', 'Buxar'), ('Darbhanga', 'Darbhanga'), ('East Champaran', 'East Champaran'), ('Gaya', 'Gaya'), ('Gopalganj', 'Gopalganj'), ('Jamui', 'Jamui'), ('Jehanabad', 'Jehanabad'), ('Kaimur', 'Kaimur'), ('Katihar', 'Katihar'), ('Khagaria', 'Khagaria'), ('Kishanganj', 'Kishanganj'), ('Lakhisarai', 'Lakhisarai'), ('Madhepura', 'Madhepura'), ('Madhubani', 'Madhubani'), ('Munger', 'Munger'), ('Muzaffarpur', 'Muzaffarpur'), ('Nalanda', 'Nalanda'), ('Nawada', 'Nawada'), ('Patna', 'Patna'), ('Purnia', 'Purnia'), ('Rohtas', 'Rohtas'), ('Saharsa', 'Saharsa'), ('Samastipur', 'Samastipur'), ('Saran', 'Saran'), ('Sheikhpura', 'Sheikhpura'), ('Sheohar', 'Sheohar'), ('Sitamarhi', 'Sitamarhi'), ('Siwan', 'Siwan'), ('Supaul', 'Supaul'), ('Vaishali', 'Vaishali'), ('West Champaran', 'West Champaran')], max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NSSUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nss_units', to='colleges.college')),
            ],
            options={
                'ordering': ['college', 'unit_number'],
                'unique_together': {('college', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='ProgramOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nss_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='colleges.nssunit')),
            ],
            options={
                'ordering': ['nss_unit', 'name'],
            },
        ),
    ]
