# Generated by Django 6.0.3 on 2026-06-28 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=100)),
                ('district', models.CharField(choices=[('Araria', 'Araria'), ('Arwal', 'Arwal'), ('Aurangabad', 'Aurangabad'), ('Banka', 'Banka'), ('Begusarai', 'Begusarai'), ('Bhagalpur', 'Bhagalpur'), ('Bhojpur', 'Bhojpur'), ('Buxar', 'Buxar'), ('Darbhanga', 'Darbhanga'), ('East Champaran', 'East Champaran'), ('Gaya', 'Gaya'), ('Gopalganj', 'Gopalganj'), ('Jamui', 'Jamui'), ('Jehanabad', 'Jehanabad'), ('Kaimur', 'Kaimur'), ('Katihar', 'Katihar'), ('Khagaria', 'Khagaria'), ('Kishanganj', 'Kishanganj'), ('Lakhisarai', 'Lakhisarai'), ('Madhepura', 'Madhepura'), ('Madhubani', 'Madhubani'), ('Munger', 'Munger'), ('Muzaffarpur', 'Muzaffarpur'), ('Nalanda', 'Nalanda'), ('Nawada', 'Nawada'), ('Patna', 'Patna'), ('Purnia', 'Purnia'), ('Rohtas', 'Rohtas'), ('Saharsa', 'Saharsa'), ('Samastipur', 'Samastipur'), ('Saran', 'Saran'), ('Sheikhpura', 'Sheikhpura'), ('Sheohar', 'Sheohar'), ('Sitamarhi', 'Sitamarhi'), ('Siwan', 'Siwan'), ('Supaul', 'Supaul'), ('Vaishali', 'Vaishali'), ('West Champaran', 'West Champaran')], db_index=True, max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='reports_images/')),
                ('after_photo', models.ImageField(blank=True, null=True, upload_to='reports_images/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('in_progress', 'In Progress'), ('cleaned', 'Cleaned')], default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('assigned_college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to='colleges.college')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
