# Generated by Django 6.0.3 on 2026-03-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issued_date']},
        ),
        migrations.AddField(
            model_name='event',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='has_participated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='district',
            field=models.CharField(choices=[('Purnea', 'Purnea'), ('Katihar', 'Katihar'), ('Araria', 'Araria'), ('Kishanganj', 'Kishanganj'), ('Madhepura', 'Madhepura'), ('Saharsa', 'Saharsa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('in_progress', 'In Progress'), ('cleaned', 'Cleaned')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='district',
            field=models.CharField(choices=[('Purnea', 'Purnea'), ('Katihar', 'Katihar'), ('Araria', 'Araria'), ('Kishanganj', 'Kishanganj'), ('Madhepura', 'Madhepura'), ('Saharsa', 'Saharsa')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('volunteer', 'event')},
        ),
    ]
