# Generated by Django 6.0.3 on 2026-04-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_certificate_options_event_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
