# Generated by Django 6.0.3 on 2026-04-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_volunteer_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
