# Generated by Django 6.0.3 on 2026-04-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_volunteer_otp_code_volunteer_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='program_coordinator_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
