# Generated by Django 6.0.3 on 2026-04-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_program_coordinator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='photo',
            field=models.ImageField(upload_to='reports_images/'),
        ),
    ]
