# Generated by Django 6.0.3 on 2026-04-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_report_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='google_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
