# Generated by Django 6.0.3 on 2026-04-16 18:07

import django.db.models.deletion
from django.db import migrations, models


def migrate_legacy_college_values(apps, schema_editor):
    Volunteer = apps.get_model('core', 'Volunteer')
    College = apps.get_model('core', 'College')

    existing = {}
    for idx, value in enumerate(
        Volunteer.objects.exclude(college__isnull=True).exclude(college="").values_list('college', flat=True).distinct(),
        start=1,
    ):
        label = (value or "").strip()
        if not label:
            continue
        if label in existing:
            continue

        college_obj, _ = College.objects.get_or_create(
            name=label,
            defaults={
                'city': 'Unknown',
                'district': 'Purnea',
                'code': f'LEGACY-{idx:04d}',
                'email': '',
                'phone': '',
                'website': None,
            },
        )
        existing[label] = college_obj

    for volunteer in Volunteer.objects.all():
        label = (volunteer.college or "").strip()
        if not label:
            continue

        college_obj = existing.get(label)
        if not college_obj:
            college_obj = College.objects.create(
                name=label,
                city='Unknown',
                district='Purnea',
                code=f'LEGACY-V{volunteer.id:04d}',
                email='',
                phone='',
            )
            existing[label] = college_obj

        volunteer.college_name = label
        volunteer.college = str(college_obj.id)
        volunteer.save(update_fields=['college_name', 'college'])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_report_award_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(choices=[('Purnea', 'Purnea'), ('Katihar', 'Katihar'), ('Araria', 'Araria'), ('Kishanganj', 'Kishanganj'), ('Madhepura', 'Madhepura'), ('Saharsa', 'Saharsa')], max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='activity_type',
            field=models.CharField(choices=[('cleanliness', 'Cleanliness Drive'), ('awareness', 'Awareness Campaign'), ('health', 'Health & Nutrition'), ('education', 'Education Support'), ('traffic', 'Traffic & Safety'), ('environment', 'Environment Conservation'), ('disaster', 'Disaster Relief'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='hours_per_volunteer',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='college_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('hours_required', models.DecimalField(decimal_places=2, max_digits=6)),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='core.volunteer')),
            ],
            options={
                'ordering': ['-earned_date'],
            },
        ),
        migrations.RunPython(migrate_legacy_college_values, noop_reverse),
        migrations.AlterField(
            model_name='volunteer',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='core.college'),
        ),
        migrations.CreateModel(
            name='NSSUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nss_units', to='core.college')),
            ],
            options={
                'ordering': ['college', 'unit_number'],
                'unique_together': {('college', 'unit_number')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='nss_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.nssunit'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='nss_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.nssunit'),
        ),
        migrations.CreateModel(
            name='ProgramOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nss_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='core.nssunit')),
            ],
            options={
                'ordering': ['nss_unit', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('cleanliness', 'Cleanliness Drive'), ('awareness', 'Awareness Campaign'), ('health', 'Health & Nutrition'), ('education', 'Education Support'), ('traffic', 'Traffic & Safety'), ('environment', 'Environment Conservation'), ('disaster', 'Disaster Relief'), ('other', 'Other')], max_length=50)),
                ('proposed_date', models.DateField()),
                ('proposed_location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('estimated_volunteers', models.IntegerField(default=10)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('approval_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal', to='core.event')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_submitted', to='core.volunteer')),
                ('nss_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='core.nssunit')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_approved', to='core.programofficer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_records', to='core.event')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_hours', to='core.volunteer')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'unique_together': {('volunteer', 'event')},
            },
        ),
    ]
