# Generated by AI: add report assignment fields
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_part5_updated_at_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='assigned_college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to='core.college'),
        ),
        migrations.AddField(
            model_name='report',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
